'0': 'Lying'
'1': 'Sitting'
'2': 'Standing'
'3': 'Walking'
'4': 'Running'
'5': 'Cycling'
'6': 'Nordic_Walking'
'7': 'Watching_TV'
'8': 'Computer_Work'
'9': 'Car_Driving'
'10': 'Ascending_Stairs'
'11': 'Descending_Stairs'
'12': 'Vacuum_Cleaning'
'13': 'Ironing'
'14': 'Folding_Laundry'
'15': 'House_Cleaning'
'16': 'Playing_Soccer'
'17': 'Rope_Jumping'
'18': 'Transient_Activities'
